routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
})->name('index');
Auth::routes(['verify' => true]);

Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');
//    \Illuminate\Support\Facades\Artisan::call('migrate');
    \Illuminate\Support\Facades\Artisan::call('storage:link');
    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');


Route::get('/user/verify/{token}', 'Auth\LoginController@activation');
// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/users', 'Backend\UserController');
        Route::post('users/excel', 'Backend\UserController@export')->name('user.export');
        Route::resource('/categories', 'Backend\CategoryController');
        Route::resource('/prospects', 'Backend\ProspectController');
        Route::get('users/prospects/{id}', 'Backend\ProspectController@usersProspects')->name('users.prospects');
        Route::post('prospect/excel', 'Backend\ProspectController@export')->name('prospect.export');
        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/contacts', 'Backend\ContactUsController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);
        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');

        // Send Notifications

        Route::resource('/notifications', 'Backend\NotificationController');


    });
    Route::prefix('counselor')->name('counselor.')->group(function () {
        Route::resource('/dashboard', 'Counselor\DashboardController');
        Route::resource('/prospects', 'Counselor\ProspectController');
        Route::post('prospect/excel', 'Counselor\ProspectController@export')->name('prospect.export');

        //User Profiles
        Route::get('profile', 'Counselor\ProfileController@index')->name('profile.index');
        Route::get('edit/profile', 'Counselor\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Counselor\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Counselor\ProfileController@updateProfile')->name('update.user.profile');
        Route::get('update/password/', 'Counselor\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Counselor\ProfileController@updatePassword')->name('update.user.password');
        Route::get('update/phone', 'Counselor\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Counselor\ProfileController@updateMobileNumber')->name('update.user.phone');

        // Send Notifications

        Route::resource('/notifications', 'Counselor\NotificationController');


    });

});


Route::get('privacy-policy', function () {
    return view('frontend.pages.privacy-policy');
})->name('privacy.policy');
Route::get('terms-and-conditions', function () {
    return view('frontend.pages.terms-and-conditions');
})->name('terms-and-conditions');

//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('role-categories', 'Backend\AjaxController@roleCategories')->name('role.categories');
    Route::get('category-service-provider', 'Backend\AjaxController@categoryServiceProvider')->name('category.service.providers');
    Route::post('click-to-read-notification', 'Backend\AjaxController@clickToReadNotification')->name('click.to.read.notification');
});

app/Http/Controllers/Backend/NotificationController.php
<?php

namespace App\Http\Controllers\Backend;


use App\Http\Controllers\Controller;
use App\Models\Notification;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Mockery\Matcher\Not;


class NotificationController extends Controller
{
    public function index(Request $request)
    {


        $users = User::whereNotIn('user_type', ['super-admin', 'prospect', 'customer'])->where('id', '!=', Auth::id())->get();
        if (isset($request->sent_to) && !is_null($request->sent_to)) {
            $notifications = Notification::where('sent_to', $request->sent_to)->get();

        } else {
            $notifications = Notification::all();
        }

        return view('backend.notification.index', compact('notifications', 'users'));
    }

    public function create()
    {
        $users = User::whereNotIn('user_type', ['super-admin', 'prospect', 'customer'])->where('id', '!=', Auth::id())->get();
        return view('backend.notification.create', compact('users'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'user_id' => 'required',
            'message' => 'required|string',
        ], [
            'user_id.required' => 'User  is required.',
            'message.required' => 'Message  is required.',
        ]);


        $notification = Notification::create([
            'sent_by' => Auth::id(),
            'sent_to' => $request->get('user_id'),
            'message' => $request->get('message'),
        ]);

        return redirect()->route('admin.notifications.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Notification send successfully.'
            ]);

    }

    public function edit($id)
    {
    }

    public function update(Request $request, $id)
    {
    }

    public function destroy($id)
    {
        $notification = Notification::findOrFail($id);
        $notification->delete();

        return redirect()->route('admin.notifications.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Notification has been deleted'
            ]);
    }
}

app/Http/Controllers/Counselor/DashboardController.php
<?php

namespace App\Http\Controllers\Counselor;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{

    public function index()
    {
        if (auth()->user()->hasRole('COUNSELORS')) {
            $users_count_prospects = User::where('user_type', 'prospect')->where('creator_id', Auth::id())->count();
            return view('counselor.dashboard.index', compact('users_count_prospects'));
        } else {
            Auth::logout();

            return redirect()->route('login')->with([
                'flash_status' => 'error',
                'flash_message' => 'You are Unauthorized for this login.'
            ]);
        }
    }
}

app/Http/Controllers/Counselor/NotificationController.php
<?php

namespace App\Http\Controllers\Counselor;
use App\Http\Controllers\Controller;
use App\Models\Notification;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NotificationController extends Controller
{
    public function index(Request $request)
    {
        $users = User::where('user_type', 'admin')->where('id', '!=', Auth::id())->get();
        if (isset($request->sent_to) && !is_null($request->sent_to)) {
            $notifications = Notification::where('sent_to', $request->sent_to)->where('sent_by', Auth::id())->get();
        } else {
            $notifications = Notification::where('sent_to', Auth::id())->orWhere('sent_by', Auth::id())->get();
        }

        return view('counselor.notification.index', compact('notifications', 'users'));
    }

    public function create()
    {
        $users = User::where('user_type', 'admin')->where('id', '!=', Auth::id())->get();
        return view('counselor.notification.create', compact('users'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'user_id' => 'required',
            'message' => 'required|string',
        ], [
            'user_id.required' => 'User  is required.',
            'message.required' => 'Message  is required.',
        ]);


        $notification = Notification::create([
            'sent_by' => Auth::id(),
            'sent_to' => $request->get('user_id'),
            'message' => $request->get('message'),
        ]);

        return redirect()->route('counselor.notifications.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Notification send successfully.'
            ]);

    }

    public function edit($id)
    {
    }

    public function update(Request $request, $id)
    {
    }

    public function destroy($id)
    {
        $notification = Notification::findOrFail($id);
        $notification->delete();

        return redirect()->route('counselor.notifications.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Notification has been deleted'
            ]);
    }
}

app/Http/Controllers/Counselor/ProfileController.php
<?php

namespace App\Http\Controllers\Counselor;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller
{
    public function __construct()
    {
    }

    public function index()
    {

        $user = auth()->user();
        return view('counselor.profiles.index', compact('user'));
    }

    public function editProfile()
    {

        $user = auth()->user();

        return view('counselor.profiles.edit-profile', compact('user'));
    }

    public function updateProfile(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required|string',
            'last_name' => 'required|string',
            'address' => 'required',
            'email' => 'required|string|email|max:255',
        ], [
            'first_name.required' => 'First name  is required.',
            'last_name.required' => 'Last name  is required.',
            'email.required' => 'Email  is required.',
        ]);

        $user = User::find(auth()->user()->id);

        $user->first_name = $request->first_name;
        $user->last_name = $request->last_name;
        $user->country = $request->country;
        $user->company = $request->company;
        $user->city = $request->city;
        $user->phone_number = $request->phone_number;
        $user->address = $request->address;
        $user->postal_code = $request->postal_code;
        $user->language = $request->language;

        $user->contact_person = $request->contact_person;
        $user->practice = $request->practice;
        $user->contract_on = $request->contract_on;
        $user->delivery = $request->delivery ?? 'no';
        $user->delivery_date = $request->delivery_date ?? null;
        $user->posters = $request->posters ?? 'no';
        $user->posters_date = $request->posters_date ?? null;
        $user->demo_kit = $request->demo_kit ?? 'no';
        $user->demo_kit_date = $request->demo_kit_date ?? null;
        $user->experience_with_cb = $request->experience_with_cb ?? null;
        $user->experience_with_at = $request->experience_with_at ?? null;
        $user->signed_contract = $request->signed_contract ?? null;
        $user->offices = $request->offices ?? null;
        $user->work_field = $request->work_field ?? null;
        $user->membership = $request->membership ?? 'no';
        $user->membership_date = $request->membership_date ?? null;
        $user->comments = $request->comments;
        $user->save();

        return redirect()->route('counselor.profile.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Profile updated successfully.'
            ]);
    }

    public function editProfileImage(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());
        $user = User::where('id', $request->user_id)->first();

        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/user_profiles');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $profile_image = $name;
        } else {
            $profile_image = $user->profile_pic;
        }
        $user->update([
            'profile_pic' => $profile_image,
        ]);

        $response['status'] = 'success';
        $response['message'] = 'Profile Image updated successfully.';

        return $response;


    }

    public function changePassword()
    {

        $user = auth()->user();
        return view('counselor.profiles.change-password', compact('user'));
    }

    public function changeMobileNumber()
    {

        $user = auth()->user();
        return view('counselor.profiles.change-mobile-number', compact('user'));
    }

    public function updateMobileNumber(Request $request)
    {
        $this->validate($request, [
            'phone_number' => 'required',
        ], [
            'phone_number.required' => 'Mobile Number is required.',

        ]);

        $user = User::find(auth()->user()->id);

        $user->update([
            'phone_number' => $request->get('phone_number'),
        ]);

        return redirect()->route('counselor.profile.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Mobile Number updated successfully.'
            ]);
    }

    public function updatePassword(Request $request)
    {
        if (!(Hash::check($request->get('current-password'), auth()->user()->password))) {
            // The passwords matches
            return redirect()->back()->with("error", "Your current password does not matches with the password you provided. Please try again.");
        }

        if (strcmp($request->get('current-password'), $request->get('new-password')) == 0) {
            //Current password and new password are same
            return redirect()->back()->with("error", "New Password cannot be same as your current password. Please choose a different password.");
        }

        $validatedData = $request->validate([
            'current-password' => 'required',
            'new-password' => 'required|string|min:6',
        ]);

        if (strcmp($request->get('new-password-confirm'), $request->get('new-password')) == 0) {
            //Change Password
            $user = Auth::user();
            $user->password = bcrypt($request->get('new-password'));
            $user->save();

            return redirect()->route('counselor.profile.index')
                ->with([
                    'flash_status' => 'success',
                    'flash_message' => 'Password Changed successfully.'
                ]);

        } else {
            return redirect()->back()->with("error", "New Password must be same as your confirm password.");
        }


    }
}

resources/views/counselor/notification/index.blade.php
@extends('counselor.layouts.master')
@section('title','Notification')
@push('css')
    <style>

        @media screen and (max-width: 650px) {
            .responsiveTable {
                overflow-x: scroll;
            }

            .responsiveTable a {
                width: 100%;
                margin: 5px 0;
            }

        }

    </style>
@endpush
@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">

            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Notification
                        </h3>
                    </div>
                </div>

                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{ route('counselor.notifications.create') }}"
                               class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Send Notification</span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="m-portlet__body">
                <form action="{{ route('counselor.notifications.index') }}" method="GET" enctype="multipart/form-data">
                    <div class="form-group row">
                        <div class="col-md-12">
                            <h4>Filter</h4>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xl-6">

                            <label for="sent_to"
                                   class="col-md-4 col-form-label text-md-left"><strong>Users:</strong></label>

                            <select id="sent_to"
                                    class="form-control states @error('sent_to') is-invalid @enderror"
                                    name="sent_to" autocomplete="sent_to">

                                <option value="">Select User</option>
                                @if(!empty($users) && count($users) >0)
                                    @foreach($users as $user)
                                        <option
                                            value="{{$user->id}}" {{ (old('sent_to') == $user->id) ? 'selected' : ''  }}> {{ ucfirst($user->first_name) }} {{ ucfirst($user->last_name) }}</option>
                                    @endforeach
                                @endif
                            </select>

                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-3">
                            <div class="m-form__actions m-form__actions">
                                <label style="display: block"
                                       class="col-md-4 col-form-label text-md-left">&nbsp;</label>
                                <a href="{{ route('counselor.notifications.index') }}"
                                   class="btn btn-accent m-btn m-btn--icon m-btn--air refreshBtn">
                                <span>
                                    <i class="la la-refresh"></i>

                                </span>
                                </a>
                                <button class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                    Submit
                                </button>
                            </div>

                        </div>
                    </div>


                </form>


                <hr>
                <div class="responsiveTable">
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                        <thead>
                        <tr>

                            <th> Sent Date</th>
                            <th> Sent By</th>
                            <th> Sent To</th>
                            <th style="width: 50%;"> Message</th>
                            <th> Is Read ?</th>
                            <th> Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(!empty($notifications))
                            @foreach($notifications as $notification)
                                <tr>
                                    <td style="width: 9%;">{{$notification->created_at ? date('d-m-Y',strtotime($notification->created_at)) : '--'}}</td>
                                    <td>{{$notification->sentByUser ? $notification->sentByUser->first_name : 'Not Found'}} {{$notification->sentByUser ? $notification->sentByUser->last_name : ''}}</td>
                                    <td>{{$notification->sentToUser ? $notification->sentToUser->first_name : 'Not Found'}} {{$notification->sentToUser ? $notification->sentToUser->last_name : ''}}</td>
                                    <td style="word-break: break-word;">{{$notification->message}}</td>
                                    <td id="isReadButton{{$notification->id}}">
                                        @if($notification->is_read == 0)
                                            <button class="btn btn-sm btn-warning"
                                                    style="border-radius: 25% !important;color: #fff">No
                                            </button>
                                        @else
                                            <button class="btn btn-sm btn-success"
                                                    style="border-radius: 25% !important;color: #fff">Yes
                                            </button>
                                        @endif
                                    </td>
                                    <td style="width: 20%;">
                                        <a href="javascript:void(0)" id="clickToRead"
                                           data-notification-id="{{$notification->id}}"
                                           data-notification-read="{{$notification->is_read}}"
                                           class="btn btn-sm btn-info pull-left notificationText{{$notification->id}} clickToRead">
                                            @if($notification->is_read == 0)
                                                Click To Read
                                            @else
                                                Click To UnRead
                                            @endif
                                        </a>
                                        <form method="post"
                                              action="{{ route('counselor.notifications.destroy', $notification->id) }}"
                                              id="delete_{{ $notification->id }}">
                                            @csrf
                                            @method('DELETE')
                                            <a class="btn btn-sm btn-danger m-left"
                                               href="javascript:void(0)"
                                               onclick="if(confirmDelete()){
                                                   document.getElementById('delete_<?=$notification->id?>').submit(); }">
                                                Delete
                                            </a>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $("select").select2();
        $("#m_table_1").dataTable({});

        $(document).on('click', '.clickToRead', function () {
            var notificationId = $(this).data('notification-id');
            var notificationReadValue = $(this).data('notification-read');
            var request = "id=" + notificationId + "&is_read=" + notificationReadValue;
            $.ajaxSetup({
                headers: {
                    'csrftoken': '<?php echo e(csrf_token()); ?>',
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                type: "POST",
                url: "{{ route('ajax.click.to.read.notification') }}",
                data: request,
                dataType: "json",
                cache: true,
                global: false,
                success: function (response) {
                    if (response.status == "success") {
                        toastr['success']("Notification Updated Successfully.");
                        var html = '';
                        if (notificationReadValue == 0) {
                            html += '<button class="btn btn-sm btn-success"  style="border-radius: 25% !important;color: #fff">Yes </button>';
                            document.getElementsByClassName(".notificationText" + notificationId + "").text = "Click To Read";
                        } else {
                            html += '<button class="btn btn-sm btn-warning"  style="border-radius: 25% !important;color: #fff">No </button>';
                            document.getElementsByClassName(".notificationText" + notificationId + "").text = "Click To UnRead";
                        }
                        $('#isReadButton' + notificationId).html(html);


                        setTimeout(function () {
                            window.location.reload();
                        }, 2000);


                    }
                },
                error: function () {
                    toastr['error']("Something Went Wrong.");
                }
            });

        });
    </script>
@endpush